// Copyright (c) 2021 Diogo Behrens, Antonio Paolillo
// SPDX-License-Identifier: MIT

/*******************************************************************************
 * Run this client code with Dartagnan to verify the correctness of the
 * CNA slowpath of qspinlock (qspinlock_cna.h) from Linux 5.14.
 * The client code can be alternatively configured to use the MCS slowpath or
 * an old version containing a liveness bug which is reproducible in hardware.
 ******************************************************************************/

/* Number of threads */
#ifndef NTHREADS
#define NTHREADS 4
#endif

/* Supported algorithms */
#define QSPINLOCK_CNA 1
#define QSPINLOCK_MCS 2
// Old version of qspicklock containing a liveness bug which is reproducible in hardware.
// This version is to be used with code generated by "make prepared LINUX_VERSION_TYPE=commit-old"
#define QSPINLOCK_MCS_OLD 3 
#ifndef ALGORITHM
#define ALGORITHM     QSPINLOCK_CNA
#endif

// This allows Dartagnan to fully unroll certain loops despite of the bound used for verification.
void __VERIFIER_loop_bound(int);

/*******************************************************************************
 * Includes, context, lock selection -- NO USER OPTIONS FROM HERE ON.
 ******************************************************************************/
#define VERIFICATION

#include <assert.h>
#include <pthread.h>
#include <stddef.h>
#include <stdbool.h>
#include <dat3m.h>

/* includes distributed in this repository */
#include <linux/atomic.h> /* some linux atomic macros */
#include <defs.h>         /* replacement of several Linux macros */

/* smp_processor_id */
__thread int tid;
#define smp_processor_id() tid

/* functions and macros to retrieve mcs/cna node (context) */

// returns a pointer to the start of the local version of nodes for cpu
static void *get_node(int cpu);

// Originally used like this
//      per_cpu_ptr(&qnodes[idx].mcs, cpu);
// Changed to be used like this
//      per_cpu_ptr(idx, cpu);
#define per_cpu_ptr(idx, cpu) &get_node(cpu)[(sizeof(struct qnode) * idx)]

// Used like this 
//      this_cpu_ptr(&qnodes[0].mcs);
#define this_cpu_ptr(p) get_node(tid)

// Used like this 
//      __this_cpu_dec(qnodes[0].mcs.count);
#define __this_cpu_dec(x) ({                                                        \
    int i = __VERIFIER_racy_read(&((struct mcs_spinlock*) this_cpu_ptr(x))->count); \
    __VERIFIER_racy_write(&((struct mcs_spinlock*) this_cpu_ptr(x))->count, i - 1); \
})
#define this_cpu_dec __this_cpu_dec

#define racy_inc(x, i)                  \
    i = __VERIFIER_racy_read(&x);       \
    __VERIFIER_racy_write(&x, i + 1);   \

/* NUMA node mapping and intra-node threshold for CNA */
#if ALGORITHM == QSPINLOCK_CNA
#define CONFIG_NUMA_AWARE_SPINLOCKS
#define cpu_to_node(x) ((x < NTHREADS/2) ? 1 : 2)
static bool cna_threshold_reached = false;
#endif

/* include qspinlock / CNA code */
#define CONFIG_NR_CPUS NTHREADS
#include <asm-generic/qspinlock.h>
#include "kernel/locking/qspinlock.c"

/* select lock and context */
#if ALGORITHM == QSPINLOCK_CNA
	struct qspinlock lock;
	/* use this instead of qnodes to make type clear in debugging */
	struct cna_node nodes[NTHREADS];
	#define init()    cna_init_nodes();
	#define nondet()  WRITE_ONCE(cna_threshold_reached, true);
#elif ALGORITHM == QSPINLOCK_MCS || ALGORITHM == QSPINLOCK_MCS_OLD
	struct qspinlock lock;
#if ALGORITHM == QSPINLOCK_MCS
	#define nodes (*qnodes)
#else
	#define nodes (*mcs_nodes)
#endif
	#define init()
	#define nondet()
#else
	#error "Invalid algorithm"
#endif

static void *get_node(int cpu) { return &nodes[cpu * MAX_NODES]; }

/*******************************************************************************
 * Client code
 ******************************************************************************/
static int x = 0, y = 0;

struct qspinlock lock_handler;

void *handle(void *arg)
{
    tid = ((intptr_t) arg);

	queued_spin_lock(&lock_handler);
	queued_spin_unlock(&lock_handler);

    return NULL;
}

static void* run(void *arg)
{
	tid = (intptr_t)arg;

    pthread_t handler;

    __VERIFIER_make_interrupt_handler();
    pthread_create(&handler, NULL, handle, tid);

	queued_spin_lock(&lock);
	x = x + 1;
	y = y + 1;
	queued_spin_unlock(&lock);

    pthread_join(handler, 0);

	return NULL;
}

int main()
{
    pthread_t t[NTHREADS];

	init();

    for (int i = 0; i < NTHREADS; i++)
        pthread_create(&t[i], 0, run, (void *)i);

   	nondet();

    for (int i = 0; i < NTHREADS; i++)
        pthread_join(t[i], 0);

   	assert (x == y);

	return 0;
}